const ActionType = {
    ADD: 'ADD',
    SUBSTRACT: 'SUBSTRACT',
    REVERT: 'REVERT',
    FETCHDATA: 'FETCHDATA',
    FETCHDATASUCCESS: 'FETCHDATASUCCESS',
    INPUTCHANGE: 'INPUTCHANGE'
}

module.exports = ActionType;